### PR TITLE
Fix issue #1008 by changing terraform plugin cache directory owner during deployer creation

### LINKED ISSUE #1008: [BUG] Deploy control plane part 2 errors with permission denied on /opt/terraform/.terraform.d/plugin-cache
**Describe the bug**
When running Deploy control plane pipeline, in job 'Deploy the control plane'  and task 'Deploy control plane part 2' would fail with error message  : 

│ Error while installing hashicorp/null v3.2.4: mkdir
│ /opt/terraform/.terraform.d/plugin-cache/registry.terraform.io: permission
│ denied
╵
╷
│ Error: Failed to install provider
│ 
│ Error while installing hashicorp/azuread v3.7.0: mkdir
│ /opt/terraform/.terraform.d/plugin-cache/registry.terraform.io: permission
│ denied
╵
╷
│ Error: Failed to install provider
│ 
│ Error while installing hashicorp/azurerm v4.55.0: mkdir
│ /opt/terraform/.terraform.d/plugin-cache/registry.terraform.io: permission
│ denied
╵
╷
│ Error: Failed to install provider
│ 
│ Error while installing hashicorp/external v2.3.5: mkdir
│ /opt/terraform/.terraform.d/plugin-cache/registry.terraform.io: permission
│ denied

**To reproduce**
1. Install SDAF on Azure DevOps by following https://learn.microsoft.com/en-us/azure/sap/automation/configure-devops?tabs=linux#configure-azure-devops-services-for-sap-deployment-automation-framework and remove  -EnableWebApp option and add -ServiceManagementReference SDAF-AzureDevOps
2. Finish the installation and execute up other necessary steps in the page above  
3. Go to https://dev.azure.com/[organizationId]/[SDAF-xxxx-xxx]
4. Click on Repos 
5. Create a new folder containing tfvars file in WORKSPACES/DEPLOYER and WORKSPACES/LIBRARY
6. Fill in both tfvars by referring to one of the sample tfvars sets in https://github.com/Azure/sap-automation-samples.git, commit them
7. Click on 'Pipelines' Icon on the left sidebar
8. Click on 'All' tab 
9. Click on Deploy Control Plane from the pipeline list
10. Click on Run pipeline button on upper right corner of screen
11. Fill in the tfvars folder names and environment name, unclick deploy config web app infrastructure and web application software (no box is checked)
12. Click Next: Resources
13. Click Run
14. Wait for the Pipeline process to execute Prepare the self hosted agent, Save the Deployment Credentials, and Deploy the control plane
15. It will fail on 'Deploy control plane part 2'

**Expected behavior** 
Continue the stage and finish the overall Deploying the Control Plane pipeline

**Additional Analysis**
Current workaround is to manually access the deployer and change the ownership  of /opt/terraform/.terraform.d directory inside the self-hosted agent (deployer VM). 

[terraform-issue.md](https://github.com/user-attachments/files/24908533/terraform-issue.md)

### PR DESCRIPTION
**Pull request by yudhiwidyatama**
## Problem

Issue #1008  where during the SDAF deployer VM preparation, the plugin cache were owned by root, so the subsequent use of self-hosted agent for terraform execution would fail with access denied error (since the agent execution will be using user azureadm, not root)

## Solution
Change the terraform plugin cache ownership in the deployer configuration template file

## Tests
By running the pipeline Deploy workload zone

### CODE REVIEW

File: deploy/terraform/terraform-units/modules/sap_deployer/templates/configure_deployer.sh.tmpl [hunk 1]
```diff
@@ -625,6 +625,8 @@ sudo chmod 755 "$${tf_bin}/terraform"
 
 sudo rm "/$${asad_home}/$${tf_zip}"
 
+chown -R "$${local_user}" "$${tf_cache}"
```
Comment (nnoaman) [inline deploy/terraform/terraform-units/modules/sap_deployer/templates/configure_deployer.sh.tmpl]:
```suggestion
sudo chown -R "$${local_user}" "$${tf_cache}"
```

**Review by nnoaman — CHANGES_REQUESTED** [review]
Thanks so much for the contribution!

I’ve targeted this PR to the release-january-2026 branch, which is the next one scheduled to be merged into main.

The fix correctly identifies the root cause: the plugin cache directory ends up being owned by root. One small thing to note is that the chown command, as written, will still require elevated privileges to modify anything under /opt/terraform, since that path is root-owned.

Suggestion: adding sudo to the command should ensure it runs successfully.

This also keeps things consistent with how the script already handles paths outside the user’s home directory.

**Comment by yudhiwidyatama** [comment]
Hi, thank you for the suggestion. On another reference (
https://github.com/Azure/custom-script-extension-linux/issues/134) it seems
that the scripts that are run by custom script extensions (like the
configure-deployer script being run by terraform module deployer using
azure virtual machine extension) would only run as root.
But I agree on your point that adding sudo would keep everything consistent.
I had updated the source code with your suggestion.

**Review by hdamecharla — APPROVED** [review]
Approved

**Review by nnoaman — APPROVED** [review]
LGTM, thanks!
